### ISSUE TITLE
Compiling the project

### ISSUE THREAD

**Issue by kaspergrubbe** [Le-Fix/gta5-quadcopter#1]
Hi!

I am having some problems compiling this project with Visual Studio 2015, most of the errors seem to be that I am missing some header files following this pattern: `inc\*.h`.

I have then looked around, and it looks like a dependency on `ScriptHookV_SDK`, and by looking at the source, maybe also `GTAVMenuBase` and `simpleini`?

Could you consider including these dependencies directly, or tell me how to install them, and where to put them so that the project will compile?

Thank you!

**Comment by Le-Fix** [comment]
My folder structure looks like:
SomeFolder
|--gta5-quadcopter (this repo)
|--GTAVMenuBase (https://github.com/E66666666/GTAVMenuBase)
|--ScriptHookV_SDK (http://www.dev-c.com/gtav/scripthookv/)

If you use the same names and they are located at the same foldr (SomeFolder), you probably don't have to change the include paths of the visual studio project.
